<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace></RootNamespace>
    <StartupObject>RegistrarDocumentRequestSystem.Program</StartupObject>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LoginForm.vb" />
    <Compile Update="LoginForm.Designer.vb">
      <DependentUpon>LoginForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="MainForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainForm.Designer.vb">
      <DependentUpon>MainForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="ReceiptForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ReceiptForm.Designer.vb">
      <DependentUpon>ReceiptForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="DocumentEditForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="DocumentEditForm.Designer.vb">
      <DependentUpon>DocumentEditForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="RequestDetailsForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="RequestDetailsForm.Designer.vb">
      <DependentUpon>RequestDetailsForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="StudentEditForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="StudentEditForm.Designer.vb">
      <DependentUpon>StudentEditForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="UpdateRequestForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UpdateRequestForm.Designer.vb">
      <DependentUpon>UpdateRequestForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="UserEditForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UserEditForm.Designer.vb">
      <DependentUpon>UserEditForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="StudentsForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="StudentsForm.Designer.vb">
      <DependentUpon>StudentsForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="DocumentsForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="DocumentsForm.Designer.vb">
      <DependentUpon>DocumentsForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="NewRequestForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="NewRequestForm.Designer.vb">
      <DependentUpon>NewRequestForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="RequestListForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="RequestListForm.Designer.vb">
      <DependentUpon>RequestListForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="ReportsForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ReportsForm.Designer.vb">
      <DependentUpon>ReportsForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>

    <Compile Update="UserAccountsForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UserAccountsForm.Designer.vb">
      <DependentUpon>UserAccountsForm.vb</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\logo.png">
      <LogicalName>Resources.logo.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="MainForm.resx">
      <DependentUpon>MainForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="StudentsForm.resx">
      <DependentUpon>StudentsForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="DocumentsForm.resx">
      <DependentUpon>DocumentsForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="NewRequestForm.resx">
      <DependentUpon>NewRequestForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="RequestListForm.resx">
      <DependentUpon>RequestListForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="ReportsForm.resx">
      <DependentUpon>ReportsForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="UserAccountsForm.resx">
      <DependentUpon>UserAccountsForm.vb</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
